name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install dprint
        uses: taiki-e/install-action@v2
        with:
          tool: dprint

      - name: Check formatting
        run: just fmt-check
